add ASG instance refresh step for api and worker deployments

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -60,7 +60,31 @@ jobs:
 
       - name: Set Auto Scaling Group Name
         run: |
-          echo "ASG_NAME=${{ inputs.environment }}-${{ inputs.module }}" >> $GITHUB_ENV
+          if [[ "${{ inputs.environment }}" == "dev" && "${{ inputs.module }}" == "worker" ]]; then
+            echo "ASG_NAME=ab2d-dev-worker" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "dev" && "${{ inputs.module }}" == "api" ]]; then
+            echo "ASG_NAME=ab2d-dev-api" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "test" && "${{ inputs.module }}" == "worker" ]]; then
+            echo "ASG_NAME=ab2d-east-impl-worker" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "test" && "${{ inputs.module }}" == "api" ]]; then
+            echo "ASG_NAME=ab2d-east-impl-api" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "sbx" && "${{ inputs.module }}" == "worker" ]]; then
+            echo "ASG_NAME=ab2d-sbx-sandbox-worker" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "sbx" && "${{ inputs.module }}" == "api" ]]; then
+            echo "ASG_NAME=ab2d-sbx-sandbox-api" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "prod" && "${{ inputs.module }}" == "worker" ]]; then
+            echo "ASG_NAME=ab2d-east-prod-worker" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "prod" && "${{ inputs.module }}" == "api" ]]; then
+            echo "ASG_NAME=ab2d-east-prod-api" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "prod_test" && "${{ inputs.module }}" == "worker" ]]; then
+            echo "ASG_NAME=ab2d-east-prod-test-worker" >> $GITHUB_ENV
+          elif [[ "${{ inputs.environment }}" == "prod_test" && "${{ inputs.module }}" == "api" ]]; then
+            echo "ASG_NAME=ab2d-east-prod-api" >> $GITHUB_ENV
+          else
+            echo "Invalid environment or module provided" && exit 1
+          fi
+          echo "Auto Scaling Group name set to: $ASG_NAME"
+
 
       - name: Start EC2 Instance Refresh
         run: |
