test

diff --git a/.github/workflows/deploy-quicksight.yml b/.github/workflows/deploy-quicksight.yml
--- a/.github/workflows/deploy-quicksight.yml
+++ b/.github/workflows/deploy-quicksight.yml
@@ -1,6 +1,10 @@
 name: deploy-quicksight
 
 on:
+  push:
+    branches:
+      - AB2D-6529/Deploy_Quicksights
+
   workflow_call:
     inputs:
       apply:
@@ -43,6 +47,9 @@ jobs:
   deploy:
     runs-on: self-hosted
 
+    env:
+      ENV: test
+
     steps:
       - name: Set environment variables
         uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
@@ -64,27 +71,42 @@ jobs:
 
       - name: Set variables for AB2D environment
         run: |
-          if [ ${{ inputs.environment }} = "dev" ]; then 
-            AB2D_ENV='ab2d-dev'
-          elif [ ${{ inputs.environment }} = "test" ]; then 
-            AB2D_ENV='ab2d-east-impl'
-          elif [ ${{ inputs.environment }} = "sbx" ]; then 
-            AB2D_ENV='ab2d-sbx-sandbox'
-          elif [ ${{ inputs.environment }} = "prod_test" ]; then 
-            AB2D_ENV='ab2d-east-prod-test'
-          elif [ ${{ inputs.environment }} = "prod" ]; then 
-            AB2D_ENV='ab2d-east-prod'
-          else 
-            echo "Unable to determine AB2D environment"; 
-            exit 1
-          fi
+           if [ "$ENV" = "dev" ]; then 
+              AB2D_ENV='ab2d-dev'
+           elif [ "$ENV" = "test" ]; then 
+              AB2D_ENV='ab2d-east-impl'
+           elif [ "$ENV" = "sbx" ]; then 
+              AB2D_ENV='ab2d-sbx-sandbox'
+           elif [ "$ENV" = "prod_test" ]; then 
+              AB2D_ENV='ab2d-east-prod-test'
+           elif [ "$ENV" = "prod" ]; then 
+              AB2D_ENV='ab2d-east-prod'
+           else 
+               echo "Unable to determine AB2D environment";
+               exit 
+               fi
+#          if [ ${{ inputs.environment }} = "dev" ]; then
+#            AB2D_ENV='ab2d-dev'
+#          elif [ ${{ inputs.environment }} = "test" ]; then
+#            AB2D_ENV='ab2d-east-impl'
+#          elif [ ${{ inputs.environment }} = "sbx" ]; then
+#            AB2D_ENV='ab2d-sbx-sandbox'
+#          elif [ ${{ inputs.environment }} = "prod_test" ]; then
+#            AB2D_ENV='ab2d-east-prod-test'
+#          elif [ ${{ inputs.environment }} = "prod" ]; then
+#            AB2D_ENV='ab2d-east-prod'
+#          else
+#            echo "Unable to determine AB2D environment";
+#            exit 1
+#          fi
           
           echo "AB2D_ENV=${AB2D_ENV}" >> $GITHUB_ENV
 
       - name: Assume role in AB2D account for this environment
         uses: aws-actions/configure-aws-credentials@v4
         env:
-          ACCOUNT: ${{ inputs.environment == 'prod_test' && 'prod' || inputs.environment }}
+          #        ACCOUNT: ${{ inputs.environment == 'prod_test' && 'prod' || inputs.environment }}
+          ACCOUNT: test
         with:
           aws-region: ${{ vars.AWS_REGION }}
           role-to-assume: arn:aws:iam::${{ secrets[format('{0}_ACCOUNT_ID', env.ACCOUNT)] }}:role/delegatedadmin/developer/ab2d-${{ env.ACCOUNT }}-github-actions
@@ -102,7 +124,7 @@ jobs:
           terraform plan -var env=${AB2D_ENV} -out=quicksight.tfplan
 
       - name: Terraform apply
-        if: ${{ inputs.apply == true }}
+      #  if: ${{ inputs.apply == true }}
         run: |
           set -e
           cd terraform/environments/ab2d/quicksight/
