WIP

diff --git a/.github/workflows/deploy-lambda.yml b/.github/workflows/deploy-lambda.yml
--- a/.github/workflows/deploy-lambda.yml
+++ b/.github/workflows/deploy-lambda.yml
@@ -104,11 +104,14 @@ jobs:
 
       - name: Determine lambdas build version
         run: |
-          echo "build version from inputs = '${{ inputs.buildVersion }}'"
-          echo "build version from job output = '${{ needs.publish_lambdas.outputs.build_version }}'"
-          buildVersion=$(echo ${{ needs.publish_lambdas.outputs.build_version || inputs.buildVersion }} | tr -d ' ')
-          echo "buildVersion=$buildVersion"
+          BUILD_VERSION=$(echo ${{ needs.publish_lambdas.outputs.build_version || inputs.buildVersion }} | tr -d ' ')
+          echo "BUILD_VERSION=${BUILD_VERSION}"
+          if [ -z "${BUILD_VERSION}" ]; then
+            echo "Unable to determine build version"
+            exit 1
+          fi  
           echo "BUILD_VERSION=$buildVersion" >> $GITHUB_ENV
+
 
       - name: Assume role in AB2D account for this environment
         uses: aws-actions/configure-aws-credentials@v3
@@ -124,7 +127,7 @@ jobs:
 
         run: |
           curl -u "${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}" "${ARTIFACTORY_PREFIX}/metrics-lambda/${BUILD_VERSION}/metrics-lambda-${BUILD_VERSION}.zip" --output metrics-lambda.zip
-          echo "$(ls)"
+          echo "$(ls -lah)"
 #          mkdir -p terraform/modules/lambda/event-service || true
 #          cd terraform/modules/lambda/event-service
 #          curl -u "${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD}" "https://artifactory.cloud.cms.gov/artifactory/ab2d-main/gov/cms/ab2d/metrics-lambda/${buildVersion//[$'\t\r\n ']}/metrics-lambda-${buildVersion//[$'\t\r\n ']}.zip" --output metrics-lambda.zip
