WIP

diff --git a/.github/workflows/deploy-lambda.yml b/.github/workflows/deploy-lambda.yml
--- a/.github/workflows/deploy-lambda.yml
+++ b/.github/workflows/deploy-lambda.yml
@@ -105,7 +105,7 @@ jobs:
           ref: ${{ inputs.ab2dOpsBranch }}
           token: ${{ env.OPS_GITHUB_TOKEN }}
 
-      - name: Determine lambdas build version
+      - name: Set variables for build version and AB2D environment
         run: |
           BUILD_VERSION=$(echo "${{ needs.publish_lambdas.outputs.build_version || inputs.buildVersion }}" | tr -d ' ')
           echo "BUILD_VERSION=${BUILD_VERSION}"
@@ -113,8 +113,17 @@ jobs:
             echo "Unable to determine build version"
             exit 1
           fi  
+          
+          if [[ ${{ inputs.environment }} = "dev" ]];         then AB2D_ENV='ab2d-dev'
+          elif [[ ${{ inputs.environment }} = "test" ]];      then AB2D_ENV='ab2d-east-impl'
+          elif [[ ${{ inputs.environment }} = "sbx" ]];       then AB2D_ENV='ab2d-sbx-sandbox'
+          elif [[ ${{ inputs.environment }} = "prod_test" ]]; then AB2D_ENV='ab2d-east-prod-test'
+          elif [[ ${{ inputs.environment }} = "prod" ]];      then AB2D_ENV='ab2d-east-prod'
+          else echo "Unable to determine AB2D environment"; exit 1
+          fi
+          
           echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_ENV
-
+          echo "AB2D_ENV=${AB2D_ENV}" >> $GITHUB_ENV
 
       - name: Assume role in AB2D account for this environment
         uses: aws-actions/configure-aws-credentials@v3
@@ -148,12 +157,7 @@ jobs:
           
           set -x
           
-          if [[ ${{ inputs.environment }} = "dev" ]];         then AB2D_ENV='ab2d-dev'
-          elif [[ ${{ inputs.environment }} = "test" ]];      then AB2D_ENV='ab2d-east-impl'
-          elif [[ ${{ inputs.environment }} = "sbx" ]];       then AB2D_ENV='ab2d-sbx-sandbox'
-          elif [[ ${{ inputs.environment }} = "prod_test" ]]; then AB2D_ENV='ab2d-east-prod-test'
-          elif [[ ${{ inputs.environment }} = "prod" ]];      then AB2D_ENV='ab2d-east-prod'
-          fi
+          
           
           terraform init -no-color -reconfigure -backend-config=backend/${AB2D_ENV}.conf
           terraform plan -no-color -var env=${AB2D_ENV} -out=lambda.tfplan
