fix

diff --git a/.github/workflows/start-job-gf.yml b/.github/workflows/start-job-gf.yml
--- a/.github/workflows/start-job-gf.yml
+++ b/.github/workflows/start-job-gf.yml
@@ -96,28 +96,28 @@ jobs:
         run: |
           sudo dnf install postgresql15 -y
 
-#      - name: Insert record
-#        run: |
-#          set -e
-#          export JOB_ID=$(uuidgen)
-#
-#          SQL_GET_ORGANIZATION=$(envsubst < .github/workflows/resources/get-organization.sql)
-#          export ORGANIZATION=$(psql -t --command="${SQL_GET_ORGANIZATION}" | head -n 1 | xargs | tr -d '\r')
-#          if [ -z "${ORGANIZATION}" ]; then
-#            echo "Unable to retrieve organization"
-#            exit 1
-#          fi
-#
-#          if [[ ${FHIR_VERSION} = "R4" ]]; then
-#            export UNTIL="'${UNTIL}'"
-#          else
-#            export UNTIL="null"
-#          fi
-#
-#          if [ -z "${API_URL_PREFIX}" ]; then
-#            export API_URL_PREFIX=${DEFAULT_API_URL_PREFIX}
-#          fi
-#
-#          SQL_INSERT_RECORD=$(envsubst < .github/workflows/resources/insert-record.sql)
-#          psql -t --command="${SQL_INSERT_RECORD}"
-#          echo "Inserted record with job UUID = $JOB_ID"
+      - name: Insert record
+        run: |
+          set -e
+          export JOB_ID=$(uuidgen)
+
+          SQL_GET_ORGANIZATION=$(envsubst < .github/workflows/resources/get-organization.sql)
+          export ORGANIZATION=$(psql -t --command="${SQL_GET_ORGANIZATION}" | head -n 1 | xargs | tr -d '\r')
+          if [ -z "${ORGANIZATION}" ]; then
+            echo "Unable to retrieve organization"
+            exit 1
+          fi
+
+          if [[ ${FHIR_VERSION} = "R4" ]]; then
+            export UNTIL="'${UNTIL}'"
+          else
+            export UNTIL="null"
+          fi
+
+          if [ -z "${API_URL_PREFIX}" ]; then
+            export API_URL_PREFIX=${DEFAULT_API_URL_PREFIX}
+          fi
+
+          SQL_INSERT_RECORD=$(envsubst < .github/workflows/resources/insert-record.sql)
+          psql -t --command="${SQL_INSERT_RECORD}"
+          echo "Inserted record with job UUID = $JOB_ID"
