set aws_account_number

diff --git a/.github/workflows/update-gold-disk.yml b/.github/workflows/update-gold-disk.yml
--- a/.github/workflows/update-gold-disk.yml
+++ b/.github/workflows/update-gold-disk.yml
@@ -51,27 +51,38 @@ jobs:
           repository: 'cmsgov/ab2d-ops'
           token: ${{ env.OPS_GITHUB_TOKEN }}
 
-      - name: Set PARENT_ENV and AWS Account
+      - name: Set PARENT_ENV and AWS_ACCOUNT_NUMBER
         run: |
           case "$ENVIRONMENT" in
-            dev) PARENT_ENV="ab2d-dev" ;;
-            test) PARENT_ENV="ab2d-east-impl" ;;
-            sbx) PARENT_ENV="ab2d-sbx-sandbox" ;;
-            prod-test) PARENT_ENV="ab2d-east-prod-test" ;;
-            prod) PARENT_ENV="ab2d-east-prod" ;;
-            *) echo "Invalid environment input: $ENVIRONMENT"; exit 1 ;;
-          esac
-
-          case "$PARENT_ENV" in
-            "ab2d-east-impl") ACCOUNT="test" ;;
-            "ab2d-dev") ACCOUNT="dev" ;;
-            "ab2d-sbx-sandbox") ACCOUNT="sbx" ;;
-            "ab2d-east-prod" | "ab2d-east-prod-test") ACCOUNT="prod" ;;
-            *) echo "Invalid PARENT_ENV"; exit 1 ;;
+            dev)
+              PARENT_ENV="ab2d-dev"
+              AWS_ACCOUNT_NUMBER="${{ secrets.DEV_ACCOUNT_ID }}"
+              ;;
+            test)
+              PARENT_ENV="ab2d-east-impl"
+              AWS_ACCOUNT_NUMBER="${{ secrets.TEST_ACCOUNT_ID }}"
+              ;;
+            sbx)
+              PARENT_ENV="ab2d-sbx-sandbox"
+              AWS_ACCOUNT_NUMBER="${{ secrets.SBX_ACCOUNT_ID }}"
+              ;;
+            prod-test)
+              PARENT_ENV="ab2d-east-prod-test"
+              AWS_ACCOUNT_NUMBER="${{ secrets.PROD_ACCOUNT_ID }}"
+              ;;
+            prod)
+              PARENT_ENV="ab2d-east-prod"
+              AWS_ACCOUNT_NUMBER="${{ secrets.PROD_ACCOUNT_ID }}"
+              ;;
+            *)
+              echo "Invalid environment input: $ENVIRONMENT"
+              exit 1
+              ;;
           esac
 
           echo "PARENT_ENV=$PARENT_ENV" >> $GITHUB_ENV
-          echo "ACCOUNT=$ACCOUNT" >> $GITHUB_ENV
+          echo "AWS_ACCOUNT_NUMBER=$AWS_ACCOUNT_NUMBER" >> $GITHUB_ENV
+
 
       - name: Assume Role in AB2D Account
         uses: aws-actions/configure-aws-credentials@v4.1.0
