add parameterization

diff --git a/.github/workflows/verify-deploy.yml b/.github/workflows/verify-deploy.yml
--- a/.github/workflows/verify-deploy.yml
+++ b/.github/workflows/verify-deploy.yml
@@ -18,6 +18,7 @@ on:
         options:
           - dev
           - test
+          - sbx
           - prod
 
 jobs:
@@ -26,7 +27,7 @@ jobs:
 
     steps:
       - name: Checkout Code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Assume role in AB2D account for this environment
         uses: aws-actions/configure-aws-credentials@v3
@@ -34,6 +35,28 @@ jobs:
           aws-region: ${{ vars.AWS_REGION }}
           role-to-assume: arn:aws:iam::330810004472:role/delegatedadmin/developer/ab2d-test-github-actions
 
+      - name: Set environment-specific variables
+        run: |
+          if [ "${{ inputs.environment }}" == "dev" ]; then
+            echo "SECRET_ID=ab2d/ab2d-dev/jenkins-verify-basic-auth" >> $GITHUB_ENV
+            echo "BASE_URL=https://dev.ab2d.cms.gov" >> $GITHUB_ENV
+            echo "EXPORT_URL=https://dev.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
+          elif [ "${{ inputs.environment }}" == "test" ]; then
+            echo "SECRET_ID=ab2d/ab2d-east-impl/jenkins-verify-api" >> $GITHUB_ENV
+            echo "BASE_URL=https://impl.ab2d.cms.gov" >> $GITHUB_ENV
+            echo "EXPORT_URL=https://impl.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
+          elif [ "${{ inputs.environment }}" == "sbx" ]; then
+            echo "SECRET_ID=ab2d/ab2d-sbx-sandbox/jenkins-verify-basic-auth" >> $GITHUB_ENV
+            echo "BASE_URL=https://sbx.ab2d.cms.gov" >> $GITHUB_ENV
+            echo "EXPORT_URL=https://sbx.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
+          elif [ "${{ inputs.environment }}" == "prod" ]; then
+            echo "SECRET_ID=ab2d/ab2d-east-prod/jenkins-verify-basic-auth" >> $GITHUB_ENV
+            echo "BASE_URL=https://api.ab2d.cms.gov" >> $GITHUB_ENV
+            echo "EXPORT_URL=https://api.ab2d.cms.gov/api/v2/fhir/Patient/$export?_type=ExplanationOfBenefit&_since=2020-02-13T00:00:00.000-05:00&_outputFormat=application%2Ffhir%2Bndjson" >> $GITHUB_ENV
+          else
+            echo "Invalid environment: ${{ inputs.environment }}"
+            exit 1
+          fi
 
       - name: Set script file based on environment
         run: echo "script=./scripts/verify-deployment-ab2d-east-impl.sh" >> $GITHUB_ENV
